config/routes.rb
Rails.application.routes.draw do
  get 'simulation/index'
  post 'simulation/exec'
  root 'simulation#index'

end

app/models/result.rb
class Result
  attr_reader :url, :area_rate
  def initialize(url, area_rate)
    @url = url
    @area_rate = area_rate
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/simulation_controller.rb
class SimulationController < ApplicationController
  def index
  end

  def exec
    @error = nil
    if params[:portal_data]
      begin
        portals = CfSim::DataFileParser.new(params[:portal_data].tempfile.path).parse
        portal_map = CfSim::PortalMap.new(portals)
        generator = CfSim::IntelMapUrlGenerator.new(portal_map)
        finder = CfSim::ControlFieldSetFinder.new(CfSim::PointList.new(portal_map.points).creatable_fields, limit_field_count: 10)
        fields_list = finder.find_max_count_fields_list
        max_area = fields_list.first.total_area
        @field_count = fields_list.first.size
        @results = fields_list.map { |fields| Result.new(generator.fields_link(fields), (fields.total_area * 100 / max_area).round(3)) }
      rescue => e
        handle_error(e)
        @error = 'File is invalid. Require CSV(latitude,longitude)'
        render status: :bad_request
      end
    end
  end

  private

  def handle_error(e)
    Rails.logger.error("#{e.class}: #{e.message}")
    e.backtrace.each { |b| Rails.logger.error("  #{b}") }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simulation_helper.rb
module SimulationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>CF Simulator</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/simulation/_result.html.erb
<% if results.present? %>
  <h2>Max field count: <%= field_count %></h2>
  <div class="list-group">
  <% results.each do |result| %>
    <a href="<%= result.url %>" class="list-group-item intel-map-url"><span class="badge"><%= result.area_rate %></span><%= result.url %></a>
  <% end %>
  </div>
<% end %>
<% if error %>
  <div class="alert alert-danger" role="alert"><%= error %></div>
<% end %>

app/views/simulation/exec.js.erb
$('#portal_data').html('<%= file_field_tag :portal_data %>');
$('#selected_file').val('');
$('#result_area').html('<%= j(render(partial: 'simulation/result', locals: { field_count: @field_count, results: @results, error: @error })) %>');

app/views/simulation/index.html.erb
<p id="upload_area">
  <%= form_tag simulation_exec_path, class: 'form-horizontal', data: { remote: true } do %>
    <div class="form-group">
      <div class="col-sm-6">
        <%= file_field_tag :portal_data %>
        <input id="selected_file" class="form-control" type="text" readonly />
      </div>
      <div claass="col-sm-2">
        <button id="select_file" class="btn btn-default" type="button"><span class="glyphicon glyphicon-folder-open"></span></button>
        <button name="upload" class="btn btn-primary"><span class="glyphicon glyphicon-upload"></span></button>
      </div>
    </div>
  <% end %>
</p>
<p id="result_area">
</p>